server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---

spring:
  config:
    activate:
      on-profile: eureka2
server:
  port: 8762

eureka:
  client:
    service-url:
      defaultZone: http://chan:8763/eureka/
  instance:
    hostname: localhost

---

spring:
  config:
    activate:
      on-profile: eureka3
server:
  port: 8763

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: chan

