spring:
  application:
    name: base-service

server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:8761/eureka
      defaultZone: http://localhost:8762/eureka, http://chan:8763/eureka
