server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Repo/native-file-repo
        git:
          uri: https://github.com/ghkddlscks19/spring-cloud-config.git
#          uri: file://C:\Repo\git-local-repo