server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ghkddlscks19/spring-cloud-config.git
#          uri: file://C:\Repo\git-local-repo